services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /data/lms-app/db:/var/lib/mysql
      # Pastikan folder 'init-db' berisi file .sql ada di server di sebelah file ini
      - ./init-db:/docker-entrypoint-initdb.d
    # ‚ùå SECURITY: Tidak ada 'ports', database tersembunyi dari dunia luar.
    networks:
      - quiz_net
  app:
    build: .
    image: lms-app:latest
    container_name: lms-app
    restart: always
    depends_on:
      - db
    # üëá INI PENGGANTI .ENV PRODUCTION KAMU
    environment:
      DATABASE_HOST: db            # Bedanya disini: pakai nama service container
      DATABASE_PORT: 3306
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_SYNC: false
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      PORT: 3000
    networks:
      - quiz_net
      - public_net

networks:
  quiz_net:
    driver: bridge
  public_net:
    external: true